name: Playwright Tests

on:
  schedule:
    - cron: "0 9 * * 3-6" 
    - cron: "0 9 * * 0"  
  workflow_dispatch:         # opcional: permite rodar manualmente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          cd "Playwright - Custódia Bradesco"
          npm install

      - name: Instalar Playwright Browsers
        run: |
          cd "Playwright - Custódia Bradesco"
          npx playwright install --with-deps

      - name: Executar Playwright
        run: |
          cd "Playwright - Custódia Bradesco"
          npx playwright test tests/BradescoNaoAssistido.spec.ts --project=chromium
