name: Playwright Tests

on:
  schedule:
    - cron: "0 9 * * 3-6" 
    - cron: "0 9 * * 0"  
  workflow_dispatch:         # opcional: permite rodar manualmente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4
    
      - name: Debug listar pastas
        run: ls -R .

